### ISSUE TITLE
Add/Remove queue needs to be implemented in Graphics Engine.

### ISSUE THREAD

**Issue by NickGrimm1** [NickGrimm1/Team3#10]
Game currently crashes on exit due to scene elements being removed before the renderer has finished the scene - recommend a queue system is implemented so that elements can't be added or removed part way through a render cycle.

**Comment by JustTh1sGuy** [comment]
Added the queues. Issue was tip of the iceberg of multi-threading problems surrounding program exit, but all sorted now.
